/* Copyright 2026 Pradyumna Revur — Apache-2.0 (see LICENSE)
   Ingredient nutrition database. Values are per 100 g (or 100 ml for
   liquids) of the raw/base ingredient as typically purchased — commonly
   published nutrition-table figures, not tied to any single copyrighted
   source. kcal/protein/carbs/fat/fiber are grams unless kcal. */
const INGREDIENTS = {
  // Grains, flours, starches
  rice_basmati_raw: { name: "Basmati rice (raw)", cat: "Grains", kcal: 360, protein: 7.9, carbs: 78, fat: 0.9, fiber: 1.3 },
  rice_cooked: { name: "Cooked rice", cat: "Grains", kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4 },
  wheat_flour: { name: "Whole-wheat flour (atta)", cat: "Grains", kcal: 340, protein: 12, carbs: 72, fat: 1.7, fiber: 11, allergens: ["gluten"] },
  maida: { name: "Refined flour (maida)", cat: "Grains", kcal: 350, protein: 10, carbs: 76, fat: 1, fiber: 2.5, allergens: ["gluten"] },
  rava: { name: "Semolina (rava/sooji)", cat: "Grains", kcal: 360, protein: 12.7, carbs: 72.8, fat: 1.1, fiber: 3.9, allergens: ["gluten"] },
  poha: { name: "Flattened rice (poha)", cat: "Grains", kcal: 356, protein: 6.6, carbs: 77, fat: 1.2, fiber: 2.3 },
  vermicelli: { name: "Vermicelli (semiya)", cat: "Grains", kcal: 348, protein: 10, carbs: 74, fat: 1.5, fiber: 2.7, allergens: ["gluten"] },
  bread_white: { name: "White bread", cat: "Grains", kcal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, allergens: ["gluten"] },
  bread_wheat: { name: "Whole-wheat bread", cat: "Grains", kcal: 247, protein: 13, carbs: 41, fat: 3.4, fiber: 7, allergens: ["gluten"] },
  pasta_dry: { name: "Pasta (dry)", cat: "Grains", kcal: 371, protein: 13, carbs: 75, fat: 1.5, fiber: 3.2, allergens: ["gluten"] },
  oats: { name: "Rolled oats", cat: "Grains", kcal: 389, protein: 16.9, carbs: 66.3, fat: 6.9, fiber: 10.6 },
  sabudana: { name: "Sabudana (tapioca pearls)", cat: "Grains", kcal: 358, protein: 0.2, carbs: 88.7, fat: 0.02, fiber: 0.9 },
  besan: { name: "Chickpea flour (besan)", cat: "Grains", kcal: 387, protein: 22, carbs: 58, fat: 6.7, fiber: 10.8 },
  poha_thick: { name: "Thick poha", cat: "Grains", kcal: 356, protein: 6.6, carbs: 77, fat: 1.2, fiber: 2.3 },
  murmura: { name: "Puffed rice (murmura)", cat: "Grains", kcal: 353, protein: 7.5, carbs: 80, fat: 0.5, fiber: 2.2 },
  bread_crumbs: { name: "Bread crumbs", cat: "Grains", kcal: 395, protein: 13, carbs: 72, fat: 5.3, fiber: 4.5, allergens: ["gluten"] },
  cornflour: { name: "Cornflour/cornstarch", cat: "Grains", kcal: 381, protein: 0.3, carbs: 91, fat: 0.1, fiber: 0.9 },
  custard_powder: { name: "Custard powder", cat: "Grains", kcal: 357, protein: 0.5, carbs: 87, fat: 0.5, fiber: 0.5 },

  // Lentils, pulses, sprouts
  moong_dal: { name: "Split moong dal", cat: "Pulses", kcal: 347, protein: 24, carbs: 59, fat: 1.2, fiber: 16.3 },
  toor_dal: { name: "Toor/arhar dal", cat: "Pulses", kcal: 343, protein: 22.3, carbs: 57.6, fat: 1.5, fiber: 15.5 },
  chana_dal: { name: "Chana dal", cat: "Pulses", kcal: 364, protein: 22.4, carbs: 61, fat: 5.3, fiber: 17 },
  masoor_dal: { name: "Masoor dal (red lentils)", cat: "Pulses", kcal: 352, protein: 25.8, carbs: 60, fat: 1.1, fiber: 11 },
  urad_dal: { name: "Urad dal", cat: "Pulses", kcal: 341, protein: 25.2, carbs: 58.9, fat: 1.6, fiber: 18 },
  rajma_cooked: { name: "Rajma (kidney beans), cooked", cat: "Pulses", kcal: 127, protein: 8.7, carbs: 22.8, fat: 0.5, fiber: 6.4 },
  chickpeas_cooked: { name: "Chickpeas (chana), cooked", cat: "Pulses", kcal: 164, protein: 8.9, carbs: 27.4, fat: 2.6, fiber: 7.6 },
  moong_sprouts: { name: "Moong sprouts", cat: "Pulses", kcal: 30, protein: 3, carbs: 6.4, fat: 0.2, fiber: 1.8, jainAvoid: true },
  peanuts: { name: "Peanuts", cat: "Pulses", kcal: 567, protein: 25.8, carbs: 16.1, fat: 49.2, fiber: 8.5, allergens: ["peanut"] },

  // Vegetables
  onion: { name: "Onion", cat: "Vegetables", kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, jainAvoid: true, gerdTrigger: true },
  tomato: { name: "Tomato", cat: "Vegetables", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, gerdTrigger: true },
  potato: { name: "Potato", cat: "Vegetables", kcal: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, jainAvoid: true },
  carrot: { name: "Carrot", cat: "Vegetables", kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8, jainAvoid: true },
  peas: { name: "Green peas", cat: "Vegetables", kcal: 81, protein: 5.4, carbs: 14.5, fat: 0.4, fiber: 5.7 },
  capsicum: { name: "Capsicum (bell pepper)", cat: "Vegetables", kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7 },
  cauliflower: { name: "Cauliflower", cat: "Vegetables", kcal: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2 },
  cabbage: { name: "Cabbage", cat: "Vegetables", kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5 },
  spinach: { name: "Spinach (palak)", cat: "Vegetables", kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2 },
  green_beans: { name: "French beans", cat: "Vegetables", kcal: 31, protein: 1.8, carbs: 7, fat: 0.2, fiber: 3.4 },
  corn: { name: "Sweet corn", cat: "Vegetables", kcal: 86, protein: 3.2, carbs: 19, fat: 1.2, fiber: 2.7 },
  cucumber: { name: "Cucumber", cat: "Vegetables", kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5 },
  beetroot: { name: "Beetroot", cat: "Vegetables", kcal: 43, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2.8, jainAvoid: true },
  garlic: { name: "Garlic", cat: "Vegetables", kcal: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, jainAvoid: true, gerdTrigger: true },
  ginger: { name: "Ginger", cat: "Vegetables", kcal: 80, protein: 1.8, carbs: 18, fat: 0.8, fiber: 2, jainAvoid: true },
  green_chili: { name: "Green chili", cat: "Vegetables", kcal: 40, protein: 2, carbs: 9, fat: 0.2, fiber: 1.5, gerdTrigger: true },
  coriander_leaves: { name: "Coriander leaves", cat: "Vegetables", kcal: 23, protein: 2.1, carbs: 3.7, fat: 0.5, fiber: 2.8 },
  mint_leaves: { name: "Mint leaves", cat: "Vegetables", kcal: 44, protein: 3.3, carbs: 8.4, fat: 0.7, fiber: 6.8, gerdTrigger: true },
  curry_leaves: { name: "Curry leaves", cat: "Vegetables", kcal: 108, protein: 6.1, carbs: 18.7, fat: 1, fiber: 6.4 },
  lemon: { name: "Lemon", cat: "Vegetables", kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, gerdTrigger: true },
  sweet_potato: { name: "Sweet potato", cat: "Vegetables", kcal: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, jainAvoid: true },
  mushroom: { name: "Mushroom", cat: "Vegetables", kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, jainAvoid: true },
  spring_onion: { name: "Spring onion", cat: "Vegetables", kcal: 32, protein: 1.8, carbs: 7.3, fat: 0.2, fiber: 2.6, jainAvoid: true, gerdTrigger: true },
  pumpkin: { name: "Pumpkin", cat: "Vegetables", kcal: 26, protein: 1, carbs: 6.5, fat: 0.1, fiber: 0.5 },
  bottle_gourd: { name: "Bottle gourd (lauki)", cat: "Vegetables", kcal: 14, protein: 0.6, carbs: 3.4, fat: 0, fiber: 0.5 },
  drumstick: { name: "Drumstick (moringa)", cat: "Vegetables", kcal: 37, protein: 2.1, carbs: 8.5, fat: 0.2, fiber: 4.8 },
  raw_banana: { name: "Raw banana/plantain", cat: "Vegetables", kcal: 122, protein: 1.3, carbs: 31.9, fat: 0.3, fiber: 2.3 },
  gongura: { name: "Gongura (sorrel leaves)", cat: "Vegetables", kcal: 45, protein: 2, carbs: 7.6, fat: 0.6, fiber: 2 },
  dosakai: { name: "Dosakai (Indian yellow cucumber)", cat: "Vegetables", kcal: 20, protein: 0.8, carbs: 4.3, fat: 0.2, fiber: 0.9 },
  brinjal: { name: "Brinjal (eggplant/vankaya)", cat: "Vegetables", kcal: 25, protein: 1, carbs: 5.9, fat: 0.2, fiber: 3, jainAvoid: true },
  chayote: { name: "Chayote squash", cat: "Vegetables", kcal: 19, protein: 0.8, carbs: 4.5, fat: 0.1, fiber: 1.7 },
  chikkudukaya: { name: "Chikkudukaya (Indian broad beans)", cat: "Vegetables", kcal: 42, protein: 2.8, carbs: 7.4, fat: 0.2, fiber: 2.9 },
  okra: { name: "Okra (bhindi)", cat: "Vegetables", kcal: 33, protein: 1.9, carbs: 7.5, fat: 0.2, fiber: 3.2 },
  dondakaya: { name: "Dondakaya (ivy gourd/tindora)", cat: "Vegetables", kcal: 17, protein: 1.2, carbs: 3.2, fat: 0.3, fiber: 1.6 },
  thotakoora: { name: "Thotakoora (amaranth leaves)", cat: "Vegetables", kcal: 23, protein: 2.5, carbs: 4, fat: 0.3, fiber: 2.1 },
  beerakaya: { name: "Beerakaya (ridge gourd)", cat: "Vegetables", kcal: 17, protein: 1.2, carbs: 3.4, fat: 0.2, fiber: 1.1 },

  // Dairy
  paneer: { name: "Paneer", cat: "Dairy", kcal: 265, protein: 18.3, carbs: 1.2, fat: 20.8, fiber: 0, allergens: ["dairy"] },
  milk: { name: "Full-cream milk", cat: "Dairy", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, allergens: ["dairy"] },
  curd: { name: "Curd/yogurt (plain)", cat: "Dairy", kcal: 60, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, allergens: ["dairy"] },
  hung_curd: { name: "Hung curd", cat: "Dairy", kcal: 110, protein: 7, carbs: 5, fat: 7, fiber: 0, allergens: ["dairy"] },
  ghee: { name: "Ghee", cat: "Dairy", kcal: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, allergens: ["dairy"] },
  butter: { name: "Butter", cat: "Dairy", kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, allergens: ["dairy"], gerdTrigger: true },
  cheese_cheddar: { name: "Cheddar cheese", cat: "Dairy", kcal: 402, protein: 25, carbs: 1.3, fat: 33, fiber: 0, allergens: ["dairy"] },
  cream: { name: "Fresh cream", cat: "Dairy", kcal: 340, protein: 2.1, carbs: 3, fat: 35, fiber: 0, allergens: ["dairy"], gerdTrigger: true },
  khoya: { name: "Khoya (milk solids)", cat: "Dairy", kcal: 421, protein: 14.6, carbs: 27, fat: 31, fiber: 0, allergens: ["dairy"] },

  // Oils & fats
  oil: { name: "Cooking oil", cat: "Fats", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0 },
  coconut_grated: { name: "Fresh coconut, grated", cat: "Fats", kcal: 354, protein: 3.3, carbs: 15.2, fat: 33.5, fiber: 9, allergens: ["tree-nut"] },
  dry_coconut: { name: "Dry coconut (desiccated)", cat: "Fats", kcal: 660, protein: 6.9, carbs: 23.7, fat: 64.5, fiber: 16.3, allergens: ["tree-nut"] },

  // Nuts, seeds, dried fruit
  cashew: { name: "Cashew nuts", cat: "Nuts", kcal: 553, protein: 18.2, carbs: 30.2, fat: 43.9, fiber: 3.3, allergens: ["tree-nut"] },
  almond: { name: "Almonds", cat: "Nuts", kcal: 579, protein: 21.2, carbs: 21.6, fat: 49.9, fiber: 12.5, allergens: ["tree-nut"] },
  raisins: { name: "Raisins", cat: "Nuts", kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7 },
  dates: { name: "Dates", cat: "Nuts", kcal: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7 },
  makhana: { name: "Makhana (fox nuts)", cat: "Nuts", kcal: 347, protein: 9.7, carbs: 76.9, fat: 0.1, fiber: 14.5 },
  sesame_seeds: { name: "Sesame seeds", cat: "Nuts", kcal: 573, protein: 17.7, carbs: 23.4, fat: 49.7, fiber: 11.8, allergens: ["sesame"] },
  walnut: { name: "Walnuts", cat: "Nuts", kcal: 654, protein: 15.2, carbs: 13.7, fat: 65.2, fiber: 6.7, allergens: ["tree-nut"] },

  // Sweeteners
  sugar: { name: "Sugar", cat: "Sweeteners", kcal: 387, protein: 0, carbs: 100, fat: 0, fiber: 0 },
  jaggery: { name: "Jaggery", cat: "Sweeteners", kcal: 383, protein: 0.4, carbs: 98, fat: 0.1, fiber: 0 },
  honey: { name: "Honey", cat: "Sweeteners", kcal: 304, protein: 0.3, carbs: 82.4, fat: 0, fiber: 0.2, jainAvoid: true },
  cocoa_powder: { name: "Cocoa powder", cat: "Sweeteners", kcal: 228, protein: 19.6, carbs: 57.9, fat: 13.7, fiber: 33.2, gerdTrigger: true },

  // Spices & condiments (small quantities; nutrition contribution is minor)
  turmeric: { name: "Turmeric powder", cat: "Spices", kcal: 312, protein: 9.7, carbs: 67, fat: 3.3, fiber: 22.7 },
  chili_powder: { name: "Red chili powder", cat: "Spices", kcal: 282, protein: 12, carbs: 50, fat: 14, fiber: 28.7, gerdTrigger: true },
  cumin_seeds: { name: "Cumin seeds (jeera)", cat: "Spices", kcal: 375, protein: 17.7, carbs: 44.2, fat: 22.3, fiber: 10.5 },
  mustard_seeds: { name: "Mustard seeds", cat: "Spices", kcal: 508, protein: 26.1, carbs: 28.1, fat: 36.2, fiber: 12.2, allergens: ["mustard"] },
  coriander_powder: { name: "Coriander powder", cat: "Spices", kcal: 298, protein: 12.4, carbs: 55, fat: 17.8, fiber: 41.9 },
  garam_masala: { name: "Garam masala", cat: "Spices", kcal: 379, protein: 13.7, carbs: 55, fat: 14.6, fiber: 27 },
  black_pepper: { name: "Black pepper", cat: "Spices", kcal: 251, protein: 10.4, carbs: 64, fat: 3.3, fiber: 25.3, gerdTrigger: true },
  chaat_masala: { name: "Chaat masala", cat: "Spices", kcal: 300, protein: 8, carbs: 60, fat: 4, fiber: 20 },
  hing: { name: "Asafoetida (hing)", cat: "Spices", kcal: 297, protein: 4, carbs: 68, fat: 1.1, fiber: 4.1 },
  sambar_powder: { name: "Sambar powder", cat: "Spices", kcal: 325, protein: 14, carbs: 55, fat: 8, fiber: 30 },
  rasam_powder: { name: "Rasam powder", cat: "Spices", kcal: 320, protein: 13, carbs: 52, fat: 9, fiber: 32 },
  cardamom: { name: "Cardamom (ground)", cat: "Spices", kcal: 311, protein: 10.8, carbs: 68.5, fat: 6.7, fiber: 28 },
  salt: { name: "Salt", cat: "Spices", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 },
  baking_soda: { name: "Baking soda / eno", cat: "Spices", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 },
  tamarind_pulp: { name: "Tamarind pulp", cat: "Spices", kcal: 239, protein: 2.8, carbs: 62.5, fat: 0.6, fiber: 5.1, gerdTrigger: true },
  soy_sauce: { name: "Soy sauce", cat: "Spices", kcal: 53, protein: 8, carbs: 4.9, fat: 0.6, fiber: 0.8, allergens: ["soy"] },
  tomato_ketchup: { name: "Tomato ketchup", cat: "Spices", kcal: 101, protein: 1.2, carbs: 24, fat: 0.2, fiber: 0.9, gerdTrigger: true },
  vinegar: { name: "Vinegar", cat: "Spices", kcal: 18, protein: 0, carbs: 0.4, fat: 0, fiber: 0, gerdTrigger: true },
  tomato_puree: { name: "Tomato puree", cat: "Spices", kcal: 32, protein: 1.6, carbs: 7.2, fat: 0.2, fiber: 1.9, gerdTrigger: true },

  // Fruits
  banana: { name: "Banana", cat: "Fruits", kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6 },
  mango: { name: "Mango", cat: "Fruits", kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6 },
  apple: { name: "Apple", cat: "Fruits", kcal: 52, protein: 0.3, carbs: 13.8, fat: 0.2, fiber: 2.4 },
  pomegranate: { name: "Pomegranate", cat: "Fruits", kcal: 83, protein: 1.7, carbs: 18.7, fat: 1.2, fiber: 4 },
  orange: { name: "Orange", cat: "Fruits", kcal: 47, protein: 0.9, carbs: 11.8, fat: 0.1, fiber: 2.4, gerdTrigger: true },
  grapes: { name: "Grapes", cat: "Fruits", kcal: 69, protein: 0.7, carbs: 18.1, fat: 0.2, fiber: 0.9 },

  // ---- Regional Indian + international pantry ----
  // Grains, flours, wrappers
  arborio_rice: { name: "Arborio rice", cat: "Grains", kcal: 358, protein: 6.7, carbs: 80, fat: 0.6, fiber: 1.4 },
  bulgur: { name: "Bulgur wheat", cat: "Grains", kcal: 342, protein: 12.3, carbs: 76, fat: 1.3, fiber: 18.3, allergens: ["gluten"] },
  couscous: { name: "Couscous", cat: "Grains", kcal: 376, protein: 12.8, carbs: 77.4, fat: 0.6, fiber: 5, allergens: ["gluten"] },
  noodles_wheat: { name: "Wheat noodles (hakka)", cat: "Grains", kcal: 348, protein: 11.5, carbs: 71, fat: 1.8, fiber: 3, allergens: ["gluten"] },
  rice_paper: { name: "Rice paper wrappers", cat: "Grains", kcal: 330, protein: 1.5, carbs: 81, fat: 0.2, fiber: 2 },
  tortilla: { name: "Wheat tortilla", cat: "Grains", kcal: 306, protein: 8.2, carbs: 51, fat: 7.5, fiber: 3, allergens: ["gluten"] },
  phyllo_pastry: { name: "Phyllo pastry", cat: "Grains", kcal: 299, protein: 7.1, carbs: 52.5, fat: 5.8, fiber: 1.8, allergens: ["gluten"] },
  makki_flour: { name: "Maize flour (makki ka atta)", cat: "Grains", kcal: 361, protein: 6.9, carbs: 76.9, fat: 3.9, fiber: 7.3 },
  rice_flour: { name: "Rice flour", cat: "Grains", kcal: 366, protein: 6, carbs: 80, fat: 1.4, fiber: 2.4 },
  sattu: { name: "Sattu (roasted gram flour)", cat: "Grains", kcal: 413, protein: 20.6, carbs: 60, fat: 5.2, fiber: 18 },
  putnalu: { name: "Putnalu (roasted gram / dalia)", cat: "Pulses", kcal: 369, protein: 22.5, carbs: 58, fat: 5.2, fiber: 15 },
  yeast: { name: "Dry active yeast", cat: "Grains", kcal: 325, protein: 40.4, carbs: 41.2, fat: 7.6, fiber: 26.9 },

  // Pulses, beans, soy
  black_beans: { name: "Black beans, cooked", cat: "Pulses", kcal: 132, protein: 8.9, carbs: 23.7, fat: 0.5, fiber: 8.7 },
  white_beans: { name: "White beans (cannellini), cooked", cat: "Pulses", kcal: 139, protein: 9.7, carbs: 25.1, fat: 0.4, fiber: 6.3 },
  black_eyed_peas: { name: "Black-eyed peas, cooked", cat: "Pulses", kcal: 116, protein: 7.7, carbs: 20.8, fat: 0.5, fiber: 6.5 },
  urad_whole: { name: "Whole urad (black gram)", cat: "Pulses", kcal: 341, protein: 25.2, carbs: 58.9, fat: 1.6, fiber: 18 },
  brown_lentils: { name: "Brown/green lentils", cat: "Pulses", kcal: 352, protein: 24.6, carbs: 63.4, fat: 1.1, fiber: 10.7 },
  chickpeas_dry: { name: "Dried chickpeas", cat: "Pulses", kcal: 364, protein: 19.3, carbs: 60.7, fat: 6, fiber: 17.4 },
  tofu: { name: "Firm tofu", cat: "Pulses", kcal: 76, protein: 8.1, carbs: 1.9, fat: 4.8, fiber: 0.3, allergens: ["soy"] },

  // Vegetables & herbs
  zucchini: { name: "Zucchini/courgette", cat: "Vegetables", kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1 },
  avocado: { name: "Avocado", cat: "Vegetables", kcal: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7 },
  olives: { name: "Olives", cat: "Vegetables", kcal: 115, protein: 0.8, carbs: 6.3, fat: 10.7, fiber: 3.2 },
  celery: { name: "Celery", cat: "Vegetables", kcal: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6 },
  lotus_stem: { name: "Lotus stem (nadru)", cat: "Vegetables", kcal: 74, protein: 2.6, carbs: 17.2, fat: 0.1, fiber: 4.9, jainAvoid: true },
  bitter_gourd: { name: "Bitter gourd (karela)", cat: "Vegetables", kcal: 17, protein: 1, carbs: 3.7, fat: 0.2, fiber: 2.8 },
  fenugreek_leaves: { name: "Fresh fenugreek leaves (methi)", cat: "Vegetables", kcal: 49, protein: 4.4, carbs: 6, fat: 0.9, fiber: 1.1 },
  mustard_greens: { name: "Mustard greens (sarson)", cat: "Vegetables", kcal: 27, protein: 2.9, carbs: 4.7, fat: 0.4, fiber: 3.2 },
  yam: { name: "Yam (suran)", cat: "Vegetables", kcal: 118, protein: 1.5, carbs: 27.9, fat: 0.2, fiber: 4.1, jainAvoid: true },
  bamboo_shoots: { name: "Bamboo shoots", cat: "Vegetables", kcal: 27, protein: 2.6, carbs: 5.2, fat: 0.3, fiber: 2.2, jainAvoid: true },
  parsley: { name: "Flat-leaf parsley", cat: "Vegetables", kcal: 36, protein: 3, carbs: 6.3, fat: 0.8, fiber: 3.3 },
  basil: { name: "Fresh basil", cat: "Vegetables", kcal: 23, protein: 3.2, carbs: 2.6, fat: 0.6, fiber: 1.6 },
  lime: { name: "Lime", cat: "Vegetables", kcal: 30, protein: 0.7, carbs: 10.5, fat: 0.2, fiber: 2.8, gerdTrigger: true },
  bean_sprouts: { name: "Bean sprouts", cat: "Vegetables", kcal: 30, protein: 3, carbs: 5.9, fat: 0.2, fiber: 1.8 },

  // Dairy (all cheeses assumed vegetarian-rennet — see recipe notes)
  feta_cheese: { name: "Feta cheese (vegetarian rennet)", cat: "Dairy", kcal: 264, protein: 14.2, carbs: 4.1, fat: 21.3, fiber: 0, allergens: ["dairy"] },
  mozzarella: { name: "Mozzarella (vegetarian rennet)", cat: "Dairy", kcal: 280, protein: 22.2, carbs: 2.2, fat: 17.1, fiber: 0, allergens: ["dairy"] },
  parmesan: { name: "Hard grating cheese (vegetarian rennet)", cat: "Dairy", kcal: 392, protein: 35.8, carbs: 3.2, fat: 25.8, fiber: 0, allergens: ["dairy"] },

  // Nuts, seeds, pastes
  poppy_seeds: { name: "Poppy seeds (posto/khus khus)", cat: "Nuts", kcal: 525, protein: 18, carbs: 28.1, fat: 41.6, fiber: 19.5 },
  tahini: { name: "Tahini (sesame paste)", cat: "Nuts", kcal: 595, protein: 17, carbs: 21.2, fat: 53.8, fiber: 9.3, allergens: ["sesame"] },
  peanut_butter: { name: "Peanut butter", cat: "Nuts", kcal: 588, protein: 25.1, carbs: 20, fat: 50.4, fiber: 6, allergens: ["peanut"] },
  pistachios: { name: "Pistachios", cat: "Nuts", kcal: 560, protein: 20.2, carbs: 27.2, fat: 45.3, fiber: 10.6, allergens: ["tree-nut"] },
  pine_nuts: { name: "Pine nuts", cat: "Nuts", kcal: 673, protein: 13.7, carbs: 13.1, fat: 68.4, fiber: 3.7, allergens: ["tree-nut"] },

  // Fats
  olive_oil: { name: "Olive oil", cat: "Fats", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0 },
  sesame_oil: { name: "Toasted sesame oil", cat: "Fats", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, allergens: ["sesame"] },
  coconut_milk: { name: "Coconut milk", cat: "Fats", kcal: 230, protein: 2.3, carbs: 5.5, fat: 23.8, fiber: 2.2 },

  // Spices, pastes & condiments
  cumin_powder: { name: "Cumin powder", cat: "Spices", kcal: 375, protein: 17.8, carbs: 44.2, fat: 22.3, fiber: 10.5 },
  red_chili_flakes: { name: "Red chili flakes", cat: "Spices", kcal: 282, protein: 12, carbs: 50, fat: 14, fiber: 28.7, gerdTrigger: true },
  oregano_dried: { name: "Dried oregano", cat: "Spices", kcal: 265, protein: 9, carbs: 68.9, fat: 4.3, fiber: 42.5 },
  paprika: { name: "Paprika", cat: "Spices", kcal: 282, protein: 14.1, carbs: 54, fat: 12.9, fiber: 34.9 },
  cinnamon: { name: "Cinnamon", cat: "Spices", kcal: 247, protein: 4, carbs: 80.6, fat: 1.2, fiber: 53.1 },
  cloves: { name: "Cloves", cat: "Spices", kcal: 274, protein: 6, carbs: 65.5, fat: 13, fiber: 33.9 },
  bay_leaf: { name: "Bay leaf", cat: "Spices", kcal: 313, protein: 7.6, carbs: 75, fat: 8.4, fiber: 26.3 },
  fennel_seeds: { name: "Fennel seeds (saunf)", cat: "Spices", kcal: 345, protein: 15.8, carbs: 52.3, fat: 14.9, fiber: 39.8 },
  carom_seeds: { name: "Carom seeds (ajwain)", cat: "Spices", kcal: 305, protein: 15.9, carbs: 43.2, fat: 21.1, fiber: 38.6 },
  nigella_seeds: { name: "Nigella seeds (kalonji)", cat: "Spices", kcal: 400, protein: 17.8, carbs: 52.3, fat: 22.4, fiber: 40 },
  fenugreek_seeds: { name: "Fenugreek seeds (methi)", cat: "Spices", kcal: 323, protein: 23, carbs: 58.4, fat: 6.4, fiber: 24.6 },
  panch_phoron: { name: "Panch phoron (Bengali five-spice)", cat: "Spices", kcal: 380, protein: 17, carbs: 45, fat: 18, fiber: 25 },
  kasuri_methi: { name: "Kasuri methi (dried fenugreek leaves)", cat: "Spices", kcal: 300, protein: 25, carbs: 45, fat: 6, fiber: 28 },
  amchur: { name: "Amchur (dry mango powder)", cat: "Spices", kcal: 305, protein: 1.5, carbs: 74, fat: 1, fiber: 3 },
  black_salt: { name: "Black salt (kala namak)", cat: "Spices", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 },
  saffron: { name: "Saffron", cat: "Spices", kcal: 310, protein: 11.4, carbs: 65.4, fat: 5.9, fiber: 3.9 },
  miso_paste: { name: "Miso paste", cat: "Spices", kcal: 199, protein: 12.8, carbs: 26.5, fat: 6, fiber: 5.4, allergens: ["soy"] },
  kombu: { name: "Kombu (dried kelp)", cat: "Spices", kcal: 43, protein: 1.7, carbs: 9.6, fat: 0.6, fiber: 1.3 },
  gochujang: { name: "Gochujang (vegetarian)", cat: "Spices", kcal: 214, protein: 5.5, carbs: 45, fat: 1.6, fiber: 3.8, allergens: ["soy"], gerdTrigger: true },
  green_curry_paste: { name: "Thai green curry paste (vegetarian)", cat: "Spices", kcal: 200, protein: 3.5, carbs: 20, fat: 12, fiber: 4 },
  lemongrass: { name: "Lemongrass", cat: "Spices", kcal: 99, protein: 1.8, carbs: 25.3, fat: 0.5, fiber: 0 },
  ras_el_hanout: { name: "Ras el hanout", cat: "Spices", kcal: 330, protein: 12, carbs: 50, fat: 12, fiber: 30 },
  berbere: { name: "Berbere spice blend", cat: "Spices", kcal: 320, protein: 13, carbs: 50, fat: 10, fiber: 30, gerdTrigger: true },
  // Beverages
  tea_leaves: { name: "Black tea leaves", cat: "Spices", kcal: 305, protein: 20, carbs: 55, fat: 3, fiber: 10, gerdTrigger: true },
  coffee_powder: { name: "Ground coffee", cat: "Spices", kcal: 353, protein: 12, carbs: 60, fat: 15, fiber: 40, gerdTrigger: true },
  rose_syrup: { name: "Rose syrup", cat: "Sweeteners", kcal: 280, protein: 0, carbs: 70, fat: 0, fiber: 0 },
  watermelon: { name: "Watermelon", cat: "Fruits", kcal: 30, protein: 0.6, carbs: 7.6, fat: 0.2, fiber: 0.4 },
  raw_mango: { name: "Raw green mango", cat: "Fruits", kcal: 44, protein: 0.5, carbs: 11, fat: 0.3, fiber: 1.6, gerdTrigger: true },

  chili_bean_paste: { name: "Chili bean paste (doubanjiang)", cat: "Spices", kcal: 180, protein: 8, carbs: 20, fat: 8, fiber: 6, gerdTrigger: true },
};
