/* Recipe database. Every recipe is 100% vegetarian — no meat, fish, or
   egg; dairy is used freely. Ingredient quantities carry both a
   human-readable qty and a gram weight so nutrition can be computed from
   js/ingredients.js. Steps and recipe text are original. */
const RECIPES = [
  // ---------------- SOUPS ----------------
  {
    id: "tomato_soup", name: "Tomato Soup", category: "soup",
    tags: ["quick", "one-pot", "kids-friendly"], time: { prep: 5, cook: 15 }, servings: 3,
    ingredients: [
      { id: "tomato", qty: "5 medium", grams: 500 },
      { id: "onion", qty: "1 small", grams: 60 },
      { id: "garlic", qty: "2 cloves", grams: 6 },
      { id: "butter", qty: "1 tbsp", grams: 14 },
      { id: "sugar", qty: "1 tsp", grams: 4 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 3 },
      { id: "cornflour", qty: "1 tsp (optional, to thicken)", grams: 3 },
    ],
    steps: [
      "Roughly chop tomatoes, onion and garlic; simmer in 2 cups water for 10 minutes until tomatoes are mushy.",
      "Cool slightly and blend smooth; pass through a sieve for a silkier soup if you like.",
      "Return to the pot with butter, sugar, pepper and salt; whisk the cornflour into a little cold water and stir in to thicken.",
      "Simmer 3–4 minutes and serve hot, topped with a swirl of cream if you have it.",
    ],
  },
  {
    id: "sweet_corn_soup", name: "Sweet Corn Soup", category: "soup",
    tags: ["quick", "one-pot", "kids-friendly"], time: { prep: 5, cook: 15 }, servings: 3,
    ingredients: [
      { id: "corn", qty: "1.5 cups kernels", grams: 220 },
      { id: "carrot", qty: "1 small, finely diced", grams: 40 },
      { id: "spring_onion", qty: "2 stalks, chopped", grams: 20 },
      { id: "garlic", qty: "2 cloves, minced", grams: 6 },
      { id: "cornflour", qty: "1.5 tbsp", grams: 12 },
      { id: "oil", qty: "1 tsp", grams: 5 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Blitz half the corn with a cup of water to a coarse paste; keep the rest whole for texture.",
      "Sauté garlic and carrot in oil for a minute, then add both corn portions and 2.5 cups water; simmer 8 minutes.",
      "Mix cornflour with a little cold water and stir in to thicken for 2 minutes.",
      "Season with pepper and salt, finish with spring onion, and serve hot.",
    ],
  },
  {
    id: "lemon_coriander_soup", name: "Lemon Coriander Soup", category: "soup",
    tags: ["quick", "one-pot", "light"], time: { prep: 5, cook: 10 }, servings: 3,
    ingredients: [
      { id: "carrot", qty: "1 small, julienned", grams: 40 },
      { id: "cabbage", qty: "1/2 cup, shredded", grams: 45 },
      { id: "capsicum", qty: "1/4, julienned", grams: 30 },
      { id: "ginger", qty: "1/2 inch, minced", grams: 5 },
      { id: "garlic", qty: "2 cloves, minced", grams: 6 },
      { id: "coriander_leaves", qty: "3 tbsp, chopped", grams: 12 },
      { id: "cornflour", qty: "1 tbsp", grams: 8 },
      { id: "lemon", qty: "1, juiced", grams: 15 },
      { id: "oil", qty: "1 tsp", grams: 5 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Sauté ginger, garlic and the vegetables in oil for 2 minutes on high heat.",
      "Add 3 cups water and simmer 6 minutes until vegetables are just tender.",
      "Stir in cornflour slurry to lightly thicken, then remove from heat.",
      "Finish with lemon juice, coriander, pepper and salt — do not reboil after adding lemon.",
    ],
  },
  {
    id: "mixed_veg_soup", name: "Mixed Vegetable Soup", category: "soup",
    tags: ["quick", "one-pot", "high-fiber"], time: { prep: 8, cook: 15 }, servings: 4,
    ingredients: [
      { id: "carrot", qty: "1 medium, diced", grams: 60 },
      { id: "potato", qty: "1 small, diced", grams: 100 },
      { id: "peas", qty: "1/3 cup", grams: 50 },
      { id: "green_beans", qty: "1/2 cup, chopped", grams: 50 },
      { id: "tomato", qty: "1 medium", grams: 100 },
      { id: "onion", qty: "1 small", grams: 60 },
      { id: "butter", qty: "1 tsp", grams: 5 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Sauté onion in butter for 2 minutes, add all remaining vegetables and stir a minute more.",
      "Add 3.5 cups water, cover and simmer 12–15 minutes until vegetables are soft.",
      "Mash lightly with the back of the spoon for a rustic thickness, or blend a third of it for a smoother body.",
      "Season with pepper and salt and serve hot.",
    ],
  },
  {
    id: "palak_soup", name: "Spinach (Palak) Soup", category: "soup",
    tags: ["quick", "one-pot", "high-fiber", "iron-rich"], time: { prep: 5, cook: 12 }, servings: 3,
    ingredients: [
      { id: "spinach", qty: "4 cups, chopped", grams: 150 },
      { id: "onion", qty: "1 small", grams: 60 },
      { id: "garlic", qty: "2 cloves", grams: 6 },
      { id: "milk", qty: "1/2 cup", grams: 120 },
      { id: "butter", qty: "1 tsp", grams: 5 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Sauté onion and garlic in butter for 2 minutes, add spinach and cook until just wilted, about 2 minutes.",
      "Add 1.5 cups water, simmer 5 minutes, then cool slightly and blend smooth.",
      "Return to the pot, stir in milk, and warm through without boiling.",
      "Season with pepper and salt; serve with a swirl of cream or a squeeze of lemon.",
    ],
  },
  {
    id: "hot_sour_veg_soup", name: "Hot & Sour Vegetable Soup", category: "soup",
    tags: ["quick", "one-pot", "indo-chinese"], time: { prep: 8, cook: 12 }, servings: 3,
    ingredients: [
      { id: "cabbage", qty: "1/2 cup, shredded", grams: 45 },
      { id: "carrot", qty: "1 small, julienned", grams: 40 },
      { id: "capsicum", qty: "1/4, julienned", grams: 30 },
      { id: "mushroom", qty: "1/2 cup, sliced", grams: 35 },
      { id: "garlic", qty: "3 cloves, minced", grams: 9 },
      { id: "ginger", qty: "1/2 inch, minced", grams: 5 },
      { id: "soy_sauce", qty: "1 tbsp", grams: 16 },
      { id: "vinegar", qty: "1 tbsp", grams: 15 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "cornflour", qty: "1.5 tbsp", grams: 12 },
      { id: "oil", qty: "1 tsp", grams: 5 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Stir-fry garlic, ginger and all vegetables in hot oil for 2 minutes, keeping them crunchy.",
      "Add 3 cups water, soy sauce, vinegar and chili powder; bring to a boil.",
      "Stir in cornflour slurry and simmer 2–3 minutes until glossy and lightly thick.",
      "Adjust salt and sourness to taste and serve piping hot.",
    ],
  },

  // ---------------- MAINS ----------------
  {
    id: "jeera_rice", name: "Jeera Rice", category: "main",
    tags: ["quick", "one-pot", "kids-friendly"], time: { prep: 5, cook: 20 }, servings: 3,
    ingredients: [
      { id: "rice_basmati_raw", qty: "1.5 cups", grams: 300 },
      { id: "cumin_seeds", qty: "1.5 tsp", grams: 3 },
      { id: "ghee", qty: "1.5 tbsp", grams: 20 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Wash and soak rice for 10 minutes, then drain.",
      "Heat ghee, splutter cumin seeds until fragrant.",
      "Add rice, salt and 2.5 cups water; bring to a boil, then cover and simmer on low for 12 minutes.",
      "Rest covered for 5 minutes off heat, then fluff with a fork.",
    ],
  },
  {
    id: "veg_pulao", name: "Vegetable Pulao", category: "main",
    tags: ["one-pot", "make-ahead"], time: { prep: 10, cook: 20 }, servings: 4,
    ingredients: [
      { id: "rice_basmati_raw", qty: "2 cups", grams: 400 },
      { id: "carrot", qty: "1 medium, diced", grams: 60 },
      { id: "peas", qty: "1/2 cup", grams: 75 },
      { id: "green_beans", qty: "1/2 cup, chopped", grams: 50 },
      { id: "onion", qty: "1 medium, sliced", grams: 100 },
      { id: "ginger", qty: "1 inch", grams: 10 },
      { id: "garlic", qty: "3 cloves", grams: 9 },
      { id: "garam_masala", qty: "1 tsp", grams: 2 },
      { id: "ghee", qty: "2 tbsp", grams: 26 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Soak rice 15 minutes and drain. Sauté onion, ginger and garlic in ghee until golden.",
      "Add all vegetables and garam masala; stir-fry 2 minutes.",
      "Add rice and 3.5 cups water and salt; bring to a boil, cover and simmer 15 minutes on low.",
      "Rest 5 minutes covered, then fluff gently before serving.",
    ],
  },
  {
    id: "dal_tadka", name: "Dal Tadka", category: "main",
    tags: ["one-pot", "high-protein", "make-ahead"], time: { prep: 5, cook: 25 }, servings: 4,
    ingredients: [
      { id: "toor_dal", qty: "1 cup", grams: 200 },
      { id: "turmeric", qty: "1/2 tsp", grams: 1.5 },
      { id: "tomato", qty: "1 medium, chopped", grams: 100 },
      { id: "onion", qty: "1 small, chopped", grams: 60 },
      { id: "garlic", qty: "3 cloves", grams: 9 },
      { id: "cumin_seeds", qty: "1 tsp", grams: 2 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "ghee", qty: "1.5 tbsp", grams: 20 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Pressure-cook (or simmer 25 minutes) dal with turmeric and 3 cups water until soft; whisk smooth.",
      "In a separate pan, heat ghee, splutter cumin, then add garlic, onion and sauté until golden.",
      "Add tomato and chili powder, cook until the tomato breaks down, then pour into the cooked dal.",
      "Simmer 5 minutes, adjust consistency with water, salt, and finish with coriander.",
    ],
  },
  {
    id: "rajma_masala", name: "Rajma Masala", category: "main",
    tags: ["high-protein", "make-ahead"], time: { prep: 5, cook: 20 }, servings: 4,
    ingredients: [
      { id: "rajma_cooked", qty: "3 cups (pre-cooked/canned)", grams: 540 },
      { id: "onion", qty: "1 medium, chopped", grams: 100 },
      { id: "tomato_puree", qty: "1 cup", grams: 240 },
      { id: "ginger", qty: "1 inch", grams: 10 },
      { id: "garlic", qty: "4 cloves", grams: 12 },
      { id: "garam_masala", qty: "1 tsp", grams: 2 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "coriander_powder", qty: "1 tsp", grams: 2 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Use pre-cooked or canned rajma (soak-and-boil ahead on a weekend) to make this a weeknight-fast dish.",
      "Sauté onion, ginger and garlic in oil until golden; add tomato puree and spices, cook until oil separates.",
      "Add the rajma with a cup of its cooking liquid (or water); simmer 12–15 minutes, mashing a few beans to thicken the gravy.",
      "Adjust salt, finish with coriander, and serve hot with rice or roti.",
    ],
  },
  {
    id: "chana_masala", name: "Chana Masala", category: "main",
    tags: ["high-protein", "make-ahead"], time: { prep: 5, cook: 18 }, servings: 4,
    ingredients: [
      { id: "chickpeas_cooked", qty: "3 cups (pre-cooked/canned)", grams: 492 },
      { id: "onion", qty: "1 medium, chopped", grams: 100 },
      { id: "tomato", qty: "2 medium, chopped", grams: 200 },
      { id: "ginger", qty: "1 inch", grams: 10 },
      { id: "garlic", qty: "3 cloves", grams: 9 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "garam_masala", qty: "1 tsp", grams: 2 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Sauté onion, ginger and garlic in oil until golden, then add tomato and cook until pulpy.",
      "Stir in chili powder and garam masala, cook a minute, then add chickpeas with a splash of water.",
      "Simmer 10 minutes, mashing a few chickpeas for body.",
      "Finish with chaat masala and coriander for the classic tang, then adjust salt.",
    ],
  },
  {
    id: "paneer_bhurji", name: "Paneer Bhurji", category: "main",
    tags: ["quick", "high-protein", "kids-friendly"], time: { prep: 5, cook: 10 }, servings: 3,
    ingredients: [
      { id: "paneer", qty: "250 g, crumbled", grams: 250 },
      { id: "onion", qty: "1 medium, chopped", grams: 100 },
      { id: "tomato", qty: "1 medium, chopped", grams: 100 },
      { id: "capsicum", qty: "1/2, chopped", grams: 60 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "turmeric", qty: "1/4 tsp", grams: 1 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "oil", qty: "1 tbsp", grams: 14 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Heat oil, sauté onion and green chili until soft, then add capsicum for a minute.",
      "Add tomato, turmeric and chili powder; cook until the tomato softens.",
      "Add crumbled paneer, toss gently for 2–3 minutes just to heat through — don't overcook or it turns rubbery.",
      "Season with salt, finish with coriander, and serve with bread or roti.",
    ],
  },
  {
    id: "matar_paneer", name: "Matar Paneer", category: "main",
    tags: ["high-protein", "quick"], time: { prep: 8, cook: 15 }, servings: 4,
    ingredients: [
      { id: "paneer", qty: "250 g, cubed", grams: 250 },
      { id: "peas", qty: "1 cup", grams: 150 },
      { id: "tomato_puree", qty: "1 cup", grams: 240 },
      { id: "onion", qty: "1 medium, chopped", grams: 100 },
      { id: "ginger", qty: "1 inch", grams: 10 },
      { id: "garlic", qty: "3 cloves", grams: 9 },
      { id: "cashew", qty: "8 pieces (for creaminess)", grams: 12 },
      { id: "garam_masala", qty: "1 tsp", grams: 2 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Sauté onion, ginger, garlic and cashews in oil until golden; cool slightly and blend to a smooth paste.",
      "Return the paste to the pan with tomato puree and spices; cook until it thickens and the oil separates.",
      "Add peas and a cup of water, simmer 5 minutes, then add paneer cubes.",
      "Simmer 3–4 minutes more, adjust salt, and serve hot.",
    ],
  },
  {
    id: "veg_khichdi", name: "Vegetable Khichdi", category: "main",
    tags: ["one-pot", "quick", "comfort-food", "high-fiber"], time: { prep: 5, cook: 20 }, servings: 4,
    ingredients: [
      { id: "rice_basmati_raw", qty: "1 cup", grams: 200 },
      { id: "moong_dal", qty: "1/2 cup", grams: 100 },
      { id: "carrot", qty: "1 small, diced", grams: 40 },
      { id: "peas", qty: "1/3 cup", grams: 50 },
      { id: "potato", qty: "1 small, diced", grams: 100 },
      { id: "cumin_seeds", qty: "1 tsp", grams: 2 },
      { id: "turmeric", qty: "1/2 tsp", grams: 1.5 },
      { id: "ghee", qty: "1.5 tbsp", grams: 20 },
      { id: "hing", qty: "a pinch", grams: 0.5 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Wash rice and dal together and drain.",
      "Heat ghee, splutter cumin and hing, then add all vegetables and turmeric; stir a minute.",
      "Add rice-dal mix, salt and 4 cups water; pressure cook 3 whistles or simmer covered 18–20 minutes until soft and porridge-like.",
      "Adjust consistency with hot water and serve with a spoon of extra ghee and papad or pickle.",
    ],
  },
  {
    id: "moong_dal_cheela", name: "Moong Dal Cheela", category: "main",
    tags: ["high-protein", "quick", "gluten-free-option"], time: { prep: 15, cook: 15 }, servings: 3,
    ingredients: [
      { id: "moong_dal", qty: "1 cup, soaked 2+ hrs", grams: 200 },
      { id: "ginger", qty: "1/2 inch", grams: 5 },
      { id: "green_chili", qty: "1", grams: 5 },
      { id: "cumin_seeds", qty: "1/2 tsp", grams: 1 },
      { id: "onion", qty: "1/4 cup, finely chopped (for topping)", grams: 25 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "oil", qty: "2 tbsp (for cooking)", grams: 28 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Drain soaked moong dal and blend with ginger, green chili and a little water to a smooth, pourable batter.",
      "Stir in cumin and salt; the batter should coat the back of a spoon.",
      "Heat a griddle, pour a ladle of batter and spread into a thin round; scatter onion and coriander on top and drizzle oil around the edges.",
      "Cook 2 minutes per side until golden and crisp; repeat, and serve hot with chutney.",
    ],
  },
  {
    id: "besan_chilla", name: "Besan Chilla", category: "main",
    tags: ["quick", "high-protein", "gluten-free"], time: { prep: 10, cook: 12 }, servings: 3,
    ingredients: [
      { id: "besan", qty: "1.5 cups", grams: 150 },
      { id: "onion", qty: "1 small, finely chopped", grams: 60 },
      { id: "tomato", qty: "1 small, finely chopped", grams: 70 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "turmeric", qty: "1/4 tsp", grams: 1 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "oil", qty: "2 tbsp (for cooking)", grams: 28 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Whisk besan with turmeric, salt and water into a smooth, dosa-like batter; fold in onion, tomato, chili and coriander.",
      "Heat a griddle and pour a ladle of batter, spreading thin.",
      "Drizzle oil around the edges and cook 2–3 minutes per side until golden and crisp.",
      "Serve hot with mint or tomato chutney.",
    ],
  },
  {
    id: "curd_rice", name: "Curd Rice", category: "main",
    tags: ["no-cook-finish", "quick", "cooling", "kids-friendly"], time: { prep: 10, cook: 5 }, servings: 3,
    ingredients: [
      { id: "rice_cooked", qty: "2 cups, cooled", grams: 300 },
      { id: "curd", qty: "1.5 cups", grams: 370 },
      { id: "milk", qty: "1/4 cup", grams: 60 },
      { id: "carrot", qty: "2 tbsp, grated (optional)", grams: 20 },
      { id: "mustard_seeds", qty: "1/2 tsp", grams: 1.5 },
      { id: "curry_leaves", qty: "1 sprig", grams: 2 },
      { id: "green_chili", qty: "1, slit", grams: 5 },
      { id: "ginger", qty: "1/2 inch, minced", grams: 5 },
      { id: "oil", qty: "1 tsp", grams: 5 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Mash cooled rice lightly, then mix in curd, milk and salt until creamy.",
      "Heat oil, splutter mustard seeds, curry leaves, green chili and ginger; pour over the rice.",
      "Fold in grated carrot for crunch and colour.",
      "Chill 10 minutes before serving — it tastes best cold.",
    ],
  },
  {
    id: "poha", name: "Poha", category: "main",
    tags: ["quick", "one-pot", "breakfast", "kids-friendly"], time: { prep: 5, cook: 10 }, servings: 3,
    ingredients: [
      { id: "poha", qty: "2 cups thick poha", grams: 150 },
      { id: "onion", qty: "1 medium, chopped", grams: 100 },
      { id: "potato", qty: "1 small, diced (optional)", grams: 100 },
      { id: "peanuts", qty: "2 tbsp", grams: 18 },
      { id: "mustard_seeds", qty: "1/2 tsp", grams: 1.5 },
      { id: "curry_leaves", qty: "1 sprig", grams: 2 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "turmeric", qty: "1/2 tsp", grams: 1.5 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Rinse poha in a colander under running water until softened; drain fully and set aside.",
      "Heat oil, splutter mustard seeds and curry leaves, then sauté peanuts, onion, potato and green chili until soft.",
      "Add turmeric and salt, then fold in the poha gently; cook 2–3 minutes covered until heated through.",
      "Finish with lemon juice and coriander before serving.",
    ],
  },
  {
    id: "upma", name: "Upma", category: "main",
    tags: ["quick", "one-pot", "breakfast", "kids-friendly"], time: { prep: 5, cook: 15 }, servings: 3,
    ingredients: [
      { id: "rava", qty: "1 cup", grams: 170 },
      { id: "onion", qty: "1 small, chopped", grams: 60 },
      { id: "carrot", qty: "1 small, diced", grams: 40 },
      { id: "peas", qty: "1/4 cup", grams: 35 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "mustard_seeds", qty: "1/2 tsp", grams: 1.5 },
      { id: "curry_leaves", qty: "1 sprig", grams: 2 },
      { id: "ghee", qty: "2 tbsp", grams: 26 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Dry-roast rava on medium heat until lightly golden and aromatic; set aside.",
      "In the same pan, heat ghee, splutter mustard seeds and curry leaves, then sauté onion, chili and vegetables until soft.",
      "Add 2.5 cups water and salt, bring to a boil, then slowly stream in the roasted rava while stirring to avoid lumps.",
      "Cover and cook 3–4 minutes on low, then finish with lemon juice before serving.",
    ],
  },
  {
    id: "sabudana_khichdi", name: "Sabudana Khichdi", category: "main",
    tags: ["quick", "one-pot", "gluten-free"], time: { prep: 10, cook: 15 }, soakNote: "plus 4+ hrs soaking (do this ahead)", servings: 3,
    ingredients: [
      { id: "sabudana", qty: "1.5 cups, soaked overnight", grams: 200 },
      { id: "potato", qty: "1 medium, diced", grams: 150 },
      { id: "peanuts", qty: "1/3 cup, roasted & crushed", grams: 48 },
      { id: "green_chili", qty: "1–2, chopped", grams: 8 },
      { id: "cumin_seeds", qty: "1 tsp", grams: 2 },
      { id: "lemon", qty: "1, juiced", grams: 15 },
      { id: "ghee", qty: "2 tbsp", grams: 26 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste (rock salt traditionally)", grams: 3 },
    ],
    steps: [
      "Soak sabudana in just enough water to cover, overnight or at least 4 hours, until pearls turn soft and translucent; drain any excess water.",
      "Heat ghee, splutter cumin, sauté green chili and potato until the potato is fork-tender.",
      "Add drained sabudana and crushed peanuts; toss gently on low heat for 5–6 minutes until pearls turn glossy and translucent.",
      "Season with salt, finish with lemon juice and coriander, and serve immediately.",
    ],
  },
  {
    id: "aloo_paratha", name: "Aloo Paratha", category: "main",
    tags: ["comfort-food", "make-ahead"], time: { prep: 15, cook: 20 }, servings: 4,
    ingredients: [
      { id: "wheat_flour", qty: "2 cups (dough) + extra for rolling", grams: 240 },
      { id: "potato", qty: "3 medium, boiled & mashed", grams: 450 },
      { id: "green_chili", qty: "1–2, minced", grams: 8 },
      { id: "coriander_leaves", qty: "3 tbsp, chopped", grams: 12 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "ghee", qty: "3 tbsp (for cooking)", grams: 40 },
      { id: "salt", qty: "to taste", grams: 5 },
    ],
    steps: [
      "Knead wheat flour with water and a pinch of salt into a soft dough; rest 15 minutes (or use dough made ahead).",
      "Mix mashed potato with chili, coriander, chaat masala, chili powder and salt for the filling.",
      "Roll a dough ball into a small disc, place filling in the centre, seal edges, and roll out gently into a paratha.",
      "Cook on a hot griddle with ghee on both sides until golden-brown spots appear; serve with curd or pickle.",
    ],
  },

  // ---------------- PASTA ----------------
  {
    id: "veg_arrabbiata_pasta", name: "Vegetable Arrabbiata Pasta", category: "pasta",
    tags: ["quick", "one-pot"], time: { prep: 10, cook: 15 }, servings: 3,
    ingredients: [
      { id: "pasta_dry", qty: "250 g", grams: 250 },
      { id: "tomato_puree", qty: "1.5 cups", grams: 360 },
      { id: "capsicum", qty: "1, diced", grams: 120 },
      { id: "mushroom", qty: "1 cup, sliced", grams: 70 },
      { id: "garlic", qty: "4 cloves, sliced", grams: 12 },
      { id: "chili_powder", qty: "1/2 tsp (or dried red chili flakes)", grams: 1.5 },
      { id: "oil", qty: "2 tbsp", grams: 28 },
      { id: "cheese_cheddar", qty: "1/4 cup, grated (optional)", grams: 25 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Boil pasta in salted water until al dente; reserve half a cup of the cooking water and drain.",
      "Heat oil, sauté garlic until golden, add capsicum and mushroom and cook 2–3 minutes.",
      "Add tomato puree and chili flakes, simmer 6–8 minutes until it thickens into a sauce.",
      "Toss in the pasta with a splash of reserved water, season with salt, and top with cheese if using.",
    ],
  },
  {
    id: "aglio_olio_pasta", name: "Aglio e Olio Pasta", category: "pasta",
    tags: ["quick", "minimal-ingredients"], time: { prep: 5, cook: 15 }, servings: 2,
    ingredients: [
      { id: "pasta_dry", qty: "200 g", grams: 200 },
      { id: "garlic", qty: "6 cloves, thinly sliced", grams: 18 },
      { id: "oil", qty: "4 tbsp (olive oil if available)", grams: 56 },
      { id: "green_chili", qty: "1, sliced (or chili flakes)", grams: 5 },
      { id: "coriander_leaves", qty: "3 tbsp, chopped (or parsley)", grams: 12 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Boil pasta in well-salted water until al dente; reserve a cup of cooking water and drain.",
      "Warm oil gently and slowly cook garlic and chili on low heat until golden — do not let it brown or turn bitter.",
      "Toss in the pasta with a splash of reserved water so the oil clings and forms a light sauce.",
      "Season with salt and pepper, finish with fresh herbs, and serve immediately.",
    ],
  },
  {
    id: "veg_mac_cheese", name: "Creamy Vegetable Mac and Cheese", category: "pasta",
    tags: ["comfort-food", "kids-friendly"], time: { prep: 10, cook: 20 }, servings: 3,
    ingredients: [
      { id: "pasta_dry", qty: "250 g (elbow macaroni)", grams: 250 },
      { id: "milk", qty: "1.5 cups", grams: 360 },
      { id: "cheese_cheddar", qty: "1 cup, grated", grams: 110 },
      { id: "butter", qty: "2 tbsp", grams: 28 },
      { id: "maida", qty: "1.5 tbsp", grams: 12 },
      { id: "peas", qty: "1/2 cup", grams: 75 },
      { id: "carrot", qty: "1 small, finely diced", grams: 40 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Boil pasta with the peas and carrot together until the pasta is al dente; drain.",
      "Melt butter, whisk in maida and cook a minute, then slowly whisk in milk to make a smooth sauce.",
      "Simmer until it coats the back of a spoon, then stir in cheese until melted.",
      "Fold in the pasta and vegetables, season with salt and pepper, and serve warm.",
    ],
  },
  {
    id: "veg_primavera_pasta", name: "Vegetable Primavera Pasta", category: "pasta",
    tags: ["quick", "high-fiber"], time: { prep: 10, cook: 15 }, servings: 3,
    ingredients: [
      { id: "pasta_dry", qty: "250 g", grams: 250 },
      { id: "capsicum", qty: "1, sliced", grams: 120 },
      { id: "carrot", qty: "1 small, julienned", grams: 40 },
      { id: "green_beans", qty: "1/2 cup, chopped", grams: 50 },
      { id: "corn", qty: "1/2 cup", grams: 75 },
      { id: "garlic", qty: "3 cloves, sliced", grams: 9 },
      { id: "cream", qty: "1/3 cup (or extra milk)", grams: 50 },
      { id: "oil", qty: "2 tbsp", grams: 28 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 4 },
    ],
    steps: [
      "Boil pasta until al dente; reserve some cooking water and drain.",
      "Sauté garlic in oil, then add all the vegetables and stir-fry on high heat 3–4 minutes, keeping them crisp.",
      "Lower heat, stir in cream and a splash of pasta water to make a light sauce.",
      "Toss in the pasta, season with salt and pepper, and serve immediately.",
    ],
  },

  // ---------------- BREAD ----------------
  {
    id: "veg_grilled_sandwich", name: "Vegetable Grilled Sandwich", category: "bread",
    tags: ["quick", "kids-friendly"], time: { prep: 10, cook: 8 }, servings: 2,
    ingredients: [
      { id: "bread_wheat", qty: "4 slices", grams: 120 },
      { id: "cucumber", qty: "1/2, thinly sliced", grams: 75 },
      { id: "tomato", qty: "1 small, thinly sliced", grams: 70 },
      { id: "capsicum", qty: "1/4, thinly sliced", grams: 30 },
      { id: "onion", qty: "1/4, thinly sliced", grams: 25 },
      { id: "cheese_cheddar", qty: "2 slices (optional)", grams: 40 },
      { id: "butter", qty: "1 tbsp", grams: 14 },
      { id: "chaat_masala", qty: "1/2 tsp", grams: 1.5 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Butter one side of each bread slice.",
      "Layer cucumber, tomato, capsicum, onion and cheese between two slices, sprinkling chaat masala and salt as you go.",
      "Grill on a hot pan or sandwich press, buttered side out, until golden and crisp on both sides.",
      "Cut diagonally and serve hot with ketchup.",
    ],
  },
  {
    id: "bread_upma", name: "Bread Upma", category: "bread",
    tags: ["quick", "one-pot", "leftover-friendly"], time: { prep: 5, cook: 10 }, servings: 2,
    ingredients: [
      { id: "bread_white", qty: "6 slices, cubed", grams: 180 },
      { id: "onion", qty: "1 small, chopped", grams: 60 },
      { id: "tomato", qty: "1 small, chopped", grams: 70 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "mustard_seeds", qty: "1/2 tsp", grams: 1.5 },
      { id: "curry_leaves", qty: "1 sprig", grams: 2 },
      { id: "turmeric", qty: "1/4 tsp", grams: 1 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Heat oil, splutter mustard seeds and curry leaves, then sauté onion and green chili until soft.",
      "Add tomato and turmeric, cook until pulpy.",
      "Add bread cubes and salt, toss gently on low heat 2–3 minutes until well coated and warmed through.",
      "Finish with lemon juice and coriander before serving.",
    ],
  },
  {
    id: "bread_pakora", name: "Bread Pakora", category: "bread",
    tags: ["quick", "comfort-food"], time: { prep: 10, cook: 10 }, servings: 3,
    ingredients: [
      { id: "bread_white", qty: "6 slices", grams: 180 },
      { id: "besan", qty: "1 cup", grams: 100 },
      { id: "turmeric", qty: "1/4 tsp", grams: 1 },
      { id: "chili_powder", qty: "1/2 tsp", grams: 1.5 },
      { id: "chaat_masala", qty: "1/2 tsp", grams: 1.5 },
      { id: "oil", qty: "3 tbsp (shallow-fry)", grams: 42 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Whisk besan with turmeric, chili powder, salt and water into a smooth, thick batter.",
      "Cut each bread slice diagonally into triangles.",
      "Dip each triangle in the batter to coat well, then shallow-fry on a hot pan with oil until golden on both sides.",
      "Sprinkle chaat masala and serve hot with ketchup or chutney.",
    ],
  },
  {
    id: "bread_uttapam", name: "Bread Uttapam", category: "bread",
    tags: ["quick", "kids-friendly"], time: { prep: 10, cook: 10 }, servings: 2,
    ingredients: [
      { id: "bread_white", qty: "6 slices", grams: 180 },
      { id: "rava", qty: "1/2 cup", grams: 85 },
      { id: "curd", qty: "1/2 cup", grams: 120 },
      { id: "onion", qty: "1 small, finely chopped", grams: 60 },
      { id: "tomato", qty: "1 small, finely chopped", grams: 70 },
      { id: "green_chili", qty: "1, chopped", grams: 5 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "oil", qty: "2 tbsp (for cooking)", grams: 28 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Tear bread into pieces and blend with rava, curd and a little water into a thick, spreadable batter; rest 10 minutes.",
      "Fold in onion, tomato, green chili and coriander.",
      "Spread a ladle of batter onto a hot, oiled griddle like a thick pancake.",
      "Drizzle a little oil, cook 2–3 minutes per side until golden, and serve with chutney.",
    ],
  },
  {
    id: "paneer_bruschetta", name: "Paneer & Tomato Bruschetta", category: "bread",
    tags: ["quick", "no-cook-option", "high-protein"], time: { prep: 10, cook: 5 }, servings: 2,
    ingredients: [
      { id: "bread_wheat", qty: "4 slices", grams: 120 },
      { id: "paneer", qty: "100 g, crumbled", grams: 100 },
      { id: "tomato", qty: "1 medium, finely diced", grams: 100 },
      { id: "garlic", qty: "1 clove, minced", grams: 3 },
      { id: "oil", qty: "1.5 tbsp", grams: 20 },
      { id: "black_pepper", qty: "1/2 tsp", grams: 1 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped (or basil)", grams: 8 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Toast bread slices until lightly crisp, then rub with the cut side of a garlic clove.",
      "Mix diced tomato, crumbled paneer, oil, pepper, salt and coriander in a bowl.",
      "Pile the mixture generously onto the toasted bread.",
      "Serve immediately while the bread is still crisp.",
    ],
  },

  // ---------------- SNACKS ----------------
  {
    id: "roasted_makhana", name: "Roasted Makhana", category: "snack",
    tags: ["quick", "no-cook-option", "light"], time: { prep: 2, cook: 8 }, servings: 2,
    ingredients: [
      { id: "makhana", qty: "2 cups", grams: 40 },
      { id: "ghee", qty: "1 tbsp", grams: 13 },
      { id: "turmeric", qty: "1/4 tsp", grams: 1 },
      { id: "chili_powder", qty: "1/4 tsp", grams: 1 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Heat ghee in a pan on low-medium heat.",
      "Add makhana and roast, stirring constantly, for 6–7 minutes until crisp and lightly golden.",
      "Sprinkle turmeric, chili powder and salt, and toss to coat evenly.",
      "Cool slightly before serving — they crisp up further as they cool.",
    ],
  },
  {
    id: "trail_mix", name: "Nut & Dried Fruit Trail Mix", category: "snack",
    tags: ["no-cook", "make-ahead", "high-energy"], time: { prep: 5, cook: 0 }, servings: 4,
    ingredients: [
      { id: "almond", qty: "1/2 cup", grams: 60 },
      { id: "cashew", qty: "1/2 cup", grams: 70 },
      { id: "walnut", qty: "1/4 cup", grams: 30 },
      { id: "raisins", qty: "1/4 cup", grams: 35 },
      { id: "dates", qty: "6, chopped", grams: 48 },
    ],
    steps: [
      "Mix all nuts and dried fruit in a jar.",
      "Store airtight for up to 2 weeks.",
      "Portion into small bags for a grab-and-go desk snack.",
    ],
  },
  {
    id: "sprouts_chaat", name: "Sprouts Chaat", category: "snack",
    tags: ["no-cook", "quick", "high-protein", "high-fiber"], time: { prep: 10, cook: 0 }, servings: 2,
    ingredients: [
      { id: "moong_sprouts", qty: "1.5 cups", grams: 150 },
      { id: "onion", qty: "1/4 cup, finely chopped", grams: 25 },
      { id: "tomato", qty: "1/2 cup, finely chopped", grams: 50 },
      { id: "cucumber", qty: "1/2 cup, diced", grams: 75 },
      { id: "lemon", qty: "1, juiced", grams: 15 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Steam or quickly blanch the sprouts for 3–4 minutes if you prefer them less raw; cool.",
      "Toss sprouts with onion, tomato and cucumber.",
      "Add lemon juice, chaat masala and salt; mix well.",
      "Garnish with coriander and serve immediately for the best crunch.",
    ],
  },
  {
    id: "fruit_chaat", name: "Fruit Chaat", category: "snack",
    tags: ["no-cook", "quick", "dessert-friendly", "high-fiber"], time: { prep: 10, cook: 0 }, servings: 3,
    ingredients: [
      { id: "apple", qty: "1, diced", grams: 180 },
      { id: "banana", qty: "1, sliced", grams: 118 },
      { id: "pomegranate", qty: "1/2 cup arils", grams: 87 },
      { id: "orange", qty: "1, segmented", grams: 140 },
      { id: "grapes", qty: "1/2 cup, halved", grams: 75 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
    ],
    steps: [
      "Chop all fruit into bite-sized pieces.",
      "Toss gently with lemon juice to prevent browning.",
      "Sprinkle chaat masala just before serving and mix once more.",
      "Serve chilled.",
    ],
  },
  {
    id: "bhel_puri", name: "Bhel Puri", category: "snack",
    tags: ["no-cook", "quick", "light"], time: { prep: 10, cook: 0 }, servings: 2,
    ingredients: [
      { id: "murmura", qty: "3 cups puffed rice", grams: 60 },
      { id: "onion", qty: "1/4 cup, finely chopped", grams: 25 },
      { id: "tomato", qty: "1/2 cup, finely chopped", grams: 50 },
      { id: "potato", qty: "1 small, boiled & diced", grams: 100 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "tamarind_pulp", qty: "1.5 tbsp", grams: 22 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
      { id: "peanuts", qty: "2 tbsp, roasted", grams: 18 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "In a large bowl, combine puffed rice, onion, tomato, potato and peanuts.",
      "Add tamarind pulp, chaat masala, lemon juice and salt.",
      "Toss everything together quickly and lightly.",
      "Serve immediately, garnished with coriander, before the puffed rice softens.",
    ],
  },
  {
    id: "corn_chaat", name: "Corn Chaat", category: "snack",
    tags: ["quick", "kids-friendly", "high-fiber"], time: { prep: 5, cook: 8 }, servings: 2,
    ingredients: [
      { id: "corn", qty: "1.5 cups kernels", grams: 220 },
      { id: "onion", qty: "1/4 cup, finely chopped", grams: 25 },
      { id: "tomato", qty: "1/2 cup, finely chopped", grams: 50 },
      { id: "capsicum", qty: "1/4, finely chopped", grams: 30 },
      { id: "lemon", qty: "1, juiced", grams: 15 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "butter", qty: "1 tsp", grams: 5 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Boil or steam corn kernels until tender, about 5–6 minutes; drain well.",
      "Toss hot corn with butter so it melts through.",
      "Add onion, tomato, capsicum, lemon juice, chaat masala and salt; mix well.",
      "Garnish with coriander and serve warm or chilled.",
    ],
  },
  {
    id: "masala_peanuts", name: "Masala Peanuts", category: "snack",
    tags: ["quick", "high-protein"], time: { prep: 5, cook: 10 }, servings: 3,
    ingredients: [
      { id: "peanuts", qty: "1.5 cups", grams: 210 },
      { id: "onion", qty: "1/4 cup, finely chopped", grams: 25 },
      { id: "tomato", qty: "1/4 cup, finely chopped", grams: 25 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "chili_powder", qty: "1/4 tsp", grams: 1 },
      { id: "lemon", qty: "1/2, juiced", grams: 8 },
      { id: "oil", qty: "1 tsp", grams: 5 },
      { id: "coriander_leaves", qty: "2 tbsp, chopped", grams: 8 },
      { id: "salt", qty: "to taste", grams: 2 },
    ],
    steps: [
      "Dry-roast or lightly pan-fry peanuts in oil until crunchy and golden; cool slightly.",
      "Toss with onion, tomato, chaat masala and chili powder.",
      "Add lemon juice and salt, mix well.",
      "Garnish with coriander and serve fresh so the peanuts stay crunchy.",
    ],
  },
  {
    id: "veg_cutlet", name: "Vegetable Cutlet", category: "snack",
    tags: ["comfort-food", "make-ahead"], time: { prep: 15, cook: 15 }, servings: 4,
    ingredients: [
      { id: "potato", qty: "3 medium, boiled & mashed", grams: 450 },
      { id: "carrot", qty: "1 small, grated", grams: 40 },
      { id: "peas", qty: "1/3 cup, boiled", grams: 50 },
      { id: "bread_crumbs", qty: "1 cup (for coating + binding)", grams: 60 },
      { id: "green_chili", qty: "1, minced", grams: 5 },
      { id: "coriander_leaves", qty: "3 tbsp, chopped", grams: 12 },
      { id: "chaat_masala", qty: "1 tsp", grams: 3 },
      { id: "oil", qty: "3 tbsp (shallow-fry)", grams: 42 },
      { id: "salt", qty: "to taste", grams: 3 },
    ],
    steps: [
      "Mix mashed potato, carrot, peas, chili, coriander, chaat masala, salt and a few tablespoons of bread crumbs to bind.",
      "Shape into small patties and coat each in the remaining bread crumbs.",
      "Shallow-fry on a hot pan with oil until golden-crisp on both sides, about 3 minutes per side.",
      "Serve hot with ketchup or mint chutney.",
    ],
  },

  // ---------------- DESSERTS ----------------
  {
    id: "rava_kesari", name: "Rava Kesari (Sooji Halwa)", category: "dessert",
    tags: ["quick", "one-pot", "festive"], time: { prep: 3, cook: 12 }, servings: 4,
    ingredients: [
      { id: "rava", qty: "1 cup", grams: 170 },
      { id: "sugar", qty: "1 cup", grams: 200 },
      { id: "ghee", qty: "3 tbsp", grams: 40 },
      { id: "cashew", qty: "10 pieces", grams: 15 },
      { id: "raisins", qty: "1 tbsp", grams: 10 },
    ],
    steps: [
      "Roast rava in half the ghee until fragrant and lightly golden; set aside.",
      "Bring 2.5 cups water to a boil, then slowly stream in the roasted rava while stirring to avoid lumps.",
      "Cook covered on low for 2–3 minutes until the rava absorbs the water, then stir in sugar until it melts and thickens.",
      "Finish with the remaining ghee and cashews/raisins fried golden, then serve warm.",
    ],
  },
  {
    id: "gajar_halwa_quick", name: "Quick Gajar Halwa", category: "dessert",
    tags: ["make-ahead", "festive"], time: { prep: 10, cook: 25 }, servings: 4,
    ingredients: [
      { id: "carrot", qty: "4 cups, grated", grams: 400 },
      { id: "milk", qty: "1.5 cups", grams: 360 },
      { id: "sugar", qty: "1/2 cup", grams: 100 },
      { id: "ghee", qty: "2 tbsp", grams: 26 },
      { id: "cashew", qty: "8 pieces, chopped", grams: 12 },
      { id: "raisins", qty: "1 tbsp", grams: 10 },
    ],
    steps: [
      "Sauté grated carrot in ghee for 5 minutes until it softens and smells sweet.",
      "Add milk and simmer, stirring occasionally, for 15 minutes until the milk is mostly absorbed.",
      "Add sugar and cook 5 more minutes until it thickens further and comes together.",
      "Garnish with cashews and raisins fried in a little ghee, and serve warm.",
    ],
  },
  {
    id: "besan_ladoo", name: "Besan Ladoo", category: "dessert",
    tags: ["make-ahead", "festive"], time: { prep: 5, cook: 15 }, servings: 8,
    ingredients: [
      { id: "besan", qty: "1.5 cups", grams: 150 },
      { id: "ghee", qty: "1/2 cup", grams: 100 },
      { id: "sugar", qty: "3/4 cup, powdered", grams: 150 },
      { id: "cashew", qty: "2 tbsp, chopped", grams: 20 },
    ],
    steps: [
      "Roast besan in ghee on low heat, stirring constantly, for 10–12 minutes until deep golden and fragrant — patience here prevents a raw taste.",
      "Cool the mixture slightly, then stir in powdered sugar and chopped cashews.",
      "While still warm enough to hold shape, roll into small balls.",
      "Cool completely before storing airtight for up to two weeks.",
    ],
  },
  {
    id: "dates_nut_energy_balls", name: "Dates & Nut Energy Balls", category: "dessert",
    tags: ["no-cook", "make-ahead", "high-energy", "high-fiber"], time: { prep: 15, cook: 0 }, servings: 8,
    ingredients: [
      { id: "dates", qty: "16, pitted", grams: 128 },
      { id: "almond", qty: "1/2 cup", grams: 60 },
      { id: "cashew", qty: "1/2 cup", grams: 70 },
      { id: "sesame_seeds", qty: "2 tbsp (for coating)", grams: 18 },
      { id: "cocoa_powder", qty: "1 tbsp (optional)", grams: 5 },
    ],
    steps: [
      "Pulse dates and nuts together in a blender until it forms a sticky, coarse dough.",
      "Mix in cocoa powder if using.",
      "Roll into small balls and coat with sesame seeds.",
      "Refrigerate in an airtight box for up to 2 weeks.",
    ],
  },
  {
    id: "shrikhand", name: "Shrikhand", category: "dessert",
    tags: ["no-cook", "make-ahead", "cooling", "high-protein"], time: { prep: 10, cook: 0 }, servings: 4,
    ingredients: [
      { id: "hung_curd", qty: "2 cups", grams: 400 },
      { id: "sugar", qty: "1/2 cup, powdered", grams: 100 },
      { id: "cashew", qty: "2 tbsp, chopped", grams: 20 },
      { id: "mango", qty: "1/2 cup pulp (optional, for aam shrikhand)", grams: 82 },
    ],
    steps: [
      "Whisk hung curd until completely smooth and lump-free.",
      "Fold in powdered sugar (and mango pulp, if using) until well combined.",
      "Chill for at least an hour to let the flavours meld.",
      "Garnish with chopped cashews and serve cold.",
    ],
  },
  {
    id: "fruit_custard", name: "Fruit Custard", category: "dessert",
    tags: ["make-ahead", "kids-friendly", "cooling"], time: { prep: 10, cook: 10 }, servings: 4,
    ingredients: [
      { id: "milk", qty: "3 cups", grams: 720 },
      { id: "custard_powder", qty: "2.5 tbsp", grams: 25 },
      { id: "sugar", qty: "1/3 cup", grams: 65 },
      { id: "banana", qty: "1, sliced", grams: 118 },
      { id: "apple", qty: "1, diced", grams: 180 },
      { id: "grapes", qty: "1/2 cup, halved", grams: 75 },
      { id: "pomegranate", qty: "1/4 cup arils", grams: 44 },
    ],
    steps: [
      "Whisk custard powder into a little cold milk until smooth.",
      "Bring the remaining milk to a gentle boil, add sugar, then stir in the custard slurry.",
      "Cook, stirring constantly, for 3–4 minutes until it thickens to a custard consistency; cool to room temperature.",
      "Fold in the chopped fruit just before serving and chill for at least an hour.",
    ],
  },
];
